-- migrations/005_device_models.sql
-- Tabela słownika modeli urządzeń (zastępuje stałą DEVICE_MODELS z config.py)

CREATE TABLE IF NOT EXISTS device_models (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE COLLATE NOCASE
);

CREATE INDEX IF NOT EXISTS idx_dm_name ON device_models(name);

-- Dane domyślne (z poprzedniej stałej DEVICE_MODELS)
INSERT OR IGNORE INTO device_models (name) VALUES
    ('Albatros 8.2'),
    ('Albatros 8.3'),
    ('Albatros 8.5'),
    ('Albatros 10.3 LTE'),
    ('FM10'),
    ('FM11'),
    ('FM15 / obd'),
    ('FM120'),
    ('FM1000'),
    ('FM1010'),
    ('FM1120'),
    ('FM5300'),
    ('FMA120'),
    ('FMB001'),
    ('FMB003'),
    ('FMB010'),
    ('FMB120'),
    ('FMB122'),
    ('FMB130'),
    ('FMB140'),
    ('FMB204'),
    ('FMB630'),
    ('FMB640'),
    ('FMB641'),
    ('FMB920'),
    ('FMB6402'),
    ('FMC003'),
    ('FMC130'),
    ('FMC150 LTE'),
    ('FMC640'),
    ('FMC650'),
    ('FMC880'),
    ('FMP100'),
    ('FMT100'),
    ('Inny'),
    ('Nie dotyczy'),
    ('QUECLINK GL500'),
    ('QUECLINK GL530'),
    ('QUECLINK GV620'),
    ('SE7'),
    ('Skaut1'),
    ('Skaut2'),
    ('Skaut3'),
    ('Skaut4'),
    ('Skaut5'),
    ('Skaut 5 Pro'),
    ('Skaut 5 Pro Apteka'),
    ('Skaut 5 Pro LTE'),
    ('Skaut 5 Pro LTE v2'),
    ('Skaut6'),
    ('Skaut 8'),
    ('Skaut 8 LTE'),
    ('Skaut 8 LTE FAKRA'),
    ('Skaut 10 FAKRA'),
    ('Skaut 10 SMA'),
    ('Skaut 11'),
    ('Skaut S13'),
    ('TAT100'),
    ('TLP2-SFB'),
    ('TMT250');
